// euro_extra.cpp -- calendar and match formats of the European competitions.
//
// 1. Dates. The game asks one dispatcher (0x14157F810: competition id, vector
//    of rows {day of year, round code, leg}) for the dates of every stage it
//    schedules; FL26's rows copy the COVID 2020/21 calendar. For the
//    competitions of euro_calendar.h (generated by calendar/build_calendar.py:
//    the real 2025/26 calendar, adjusted so that every club has at least three
//    days between two matches, same days every season) this DLL answers with
//    its own rows; anything else (or a league whose club count differs from
//    the table) keeps the native rows.
//      * leagues: round r -> code r, leg 2 (single match);
//      * UEFA league phases 3/5 (four groups of 9: matchdays 1-8 + the empty
//        ninth round; old eight-group seasons: matchdays 1-6) and 77;
//      * knockout cups: the bracket size comes from the participants, the
//        round code from the game's rule (0x141557B90), the day from the stage
//        (final, semi-finals, ...); two-legged stages get legs 0 and 1.
// 2. Legs. When the game builds a cup it asks 0x14151D1E0 (competition,
//    round code) whether the round is a single match; the regulation only
//    offers "all single", "all two-legged but the final" or "all two-legged".
//    For the cups of euro_calendar.h the answer follows the real format
//    (EFL Cup, Coppa Italia, Copa del Rey, Taca de Portugal, Belgian and Greek
//    cups: two-legged semi-finals; Danish cup: quarter- and semi-finals),
//    super cups and European play-off finals are single matches.
// Nothing is written on disk except euro_extra.log.

#ifndef _WIN32_WINNT
#define _WIN32_WINNT 0x0601
#endif
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdint.h>
#include "euro_calendar.h"

static const uintptr_t kImageBase = 0x140000000ULL;
static const uintptr_t kGlobalRootPtr = kImageBase + 0x03705E10;
static const uintptr_t kModelOffset = 0x48;
static const uintptr_t kComps = 0x00C12E9C;
static const uint32_t kCompStride = 0x314;
static const uintptr_t kCompCount = 0x00D0BCF4;
static const uintptr_t kCalendar = 0x016038A8;
static const uintptr_t kCalendarDay = 0x3F174;
static const uintptr_t kPushRowFn = kImageBase + 0x01586640; // vector<DateRow>::push_back

static const uintptr_t kDispatcher = kImageBase + 0x0157F810;  // (comp, vector<DateRow>*)
static const unsigned char kDispatcherSig[17] = {               // push rbp/rbx/rdi; mov rbp,rsp;
    0x40,0x55,0x53,0x57,0x48,0x8B,0xEC,0x48,0x83,0xEC,0x20,     // sub rsp,20h; mov rbx,rdx;
    0x48,0x8B,0xDA,0x0F,0xB7,0xF9                               // movzx edi,cx
};
static const uintptr_t kSingleMatch = kImageBase + 0x0151D1E0; // bool (comp, round code)
static const unsigned char kSingleSig[15] = {                   // mov [rsp+8/10h/18h], rbx/rbp/rsi
    0x48,0x89,0x5C,0x24,0x08,0x48,0x89,0x6C,0x24,0x10,0x48,0x89,0x74,0x24,0x18
};

struct DateRow { uint32_t day, code, leg; };   // day 0 = 1 January

static const char kLogName[] = "euro_extra.log";
static CRITICAL_SECTION g_log_lock;
static bool g_log_ready = false;

static void log_line(const char* text) {
    if (!g_log_ready) return;
    SYSTEMTIME st;
    GetLocalTime(&st);
    char line[1024];
    int n = wsprintfA(line, "%02u:%02u:%02u | ", (unsigned)st.wHour, (unsigned)st.wMinute, (unsigned)st.wSecond);
    int len = lstrlenA(text);
    if (len > (int)sizeof(line) - n - 3) len = (int)sizeof(line) - n - 3;
    CopyMemory(line + n, text, len);
    n += len;
    line[n++] = '\r'; line[n++] = '\n';
    EnterCriticalSection(&g_log_lock);
    HANDLE h = CreateFileA(kLogName, FILE_APPEND_DATA, FILE_SHARE_READ, NULL,
        OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
    if (h != INVALID_HANDLE_VALUE) {
        DWORD written = 0;
        WriteFile(h, line, (DWORD)n, &written, NULL);
        CloseHandle(h);
    }
    LeaveCriticalSection(&g_log_lock);
}

static bool readable(const void* p, size_t span) {
    if (!p) return false;
    MEMORY_BASIC_INFORMATION mbi;
    if (!VirtualQuery(p, &mbi, sizeof(mbi))) return false;
    if (mbi.State != MEM_COMMIT || (mbi.Protect & PAGE_GUARD)) return false;
    DWORD ok = PAGE_READONLY | PAGE_READWRITE | PAGE_WRITECOPY |
        PAGE_EXECUTE_READ | PAGE_EXECUTE_READWRITE | PAGE_EXECUTE_WRITECOPY;
    uintptr_t a = (uintptr_t)p;
    uintptr_t end = (uintptr_t)mbi.BaseAddress + mbi.RegionSize;
    return (mbi.Protect & ok) && a >= (uintptr_t)mbi.BaseAddress && a + span <= end;
}

static bool same_bytes(uintptr_t addr, const unsigned char* want, uint32_t n) {
    if (!readable((const void*)addr, n)) return false;
    for (uint32_t i = 0; i < n; ++i) if (((const unsigned char*)addr)[i] != want[i]) return false;
    return true;
}

static bool write_code(uintptr_t addr, const void* bytes, uint32_t n) {
    DWORD old = 0, ignored = 0;
    if (!VirtualProtect((void*)addr, n, PAGE_EXECUTE_READWRITE, &old)) return false;
    CopyMemory((void*)addr, bytes, n);
    FlushInstructionCache(GetCurrentProcess(), (const void*)addr, n);
    VirtualProtect((void*)addr, n, old, &ignored);
    return same_bytes(addr, (const unsigned char*)bytes, n);
}

static void absolute_jump(unsigned char* out, uintptr_t target) {
    out[0] = 0xFF; out[1] = 0x25;
    out[2] = out[3] = out[4] = out[5] = 0;
    for (int i = 0; i < 8; ++i) out[6 + i] = (unsigned char)(target >> (i * 8));
}

// Entry hook: the prologue (whole instructions, no RIP-relative operand) moves
// to a trampoline that jumps back; the entry jumps to `handler`.
static void* hook_entry(uintptr_t fn, const unsigned char* sig, uint32_t len, void* handler) {
    if (len < 14 || len > 32 || !same_bytes(fn, sig, len)) return NULL;
    unsigned char* tramp = (unsigned char*)VirtualAlloc(NULL, 0x1000, MEM_RESERVE | MEM_COMMIT, PAGE_EXECUTE_READWRITE);
    if (!tramp) return NULL;
    CopyMemory(tramp, (const void*)fn, len);
    absolute_jump(tramp + len, fn + len);
    FlushInstructionCache(GetCurrentProcess(), tramp, len + 14);
    unsigned char patch[32];
    for (uint32_t i = 0; i < len; ++i) patch[i] = 0x90;
    absolute_jump(patch, (uintptr_t)handler);
    if (!write_code(fn, patch, len)) {
        write_code(fn, sig, len);
        VirtualFree(tramp, 0, MEM_RELEASE);
        return NULL;
    }
    return tramp;
}

static uintptr_t model_base() {
    if (!readable((const void*)kGlobalRootPtr, sizeof(uintptr_t))) return 0;
    uintptr_t root = *(const uintptr_t*)kGlobalRootPtr;
    if (!readable((const void*)(root + kModelOffset), sizeof(uintptr_t))) return 0;
    return *(const uintptr_t*)(root + kModelOffset);
}

static uintptr_t find_comp(uintptr_t model, uint16_t id) {
    if (!model || !readable((const void*)(model + kCompCount), 4)) return 0;
    uint32_t count = *(const uint32_t*)(model + kCompCount);
    if (count > 300) count = 300;
    for (uint32_t i = 0; i < count; ++i) {
        uintptr_t rec = model + kComps + (uintptr_t)i * kCompStride;
        if (!readable((const void*)rec, kCompStride)) return 0;
        if (*(const uint16_t*)rec == id) return rec;
    }
    return 0;
}

static uint32_t participants(uintptr_t rec) {
    return rec ? (*(const uint32_t*)(rec + 0x308) >> 16) & 0x7F : 0;
}

static uint32_t group_count(uintptr_t rec) {
    return rec ? *(const uint8_t*)(rec + 0x307) & 0x3F : 0;
}

#define COUNT(a) (sizeof(a) / sizeof((a)[0]))

// ------------------------------------------------------------ knockout rounds
// Round code of a round with `teams` clubs in a bracket of `total` (0x141557B90).
static uint32_t round_code(uint32_t total, uint32_t teams) {
    if (teams == 2) return 53;
    if (teams == 4) return total > 4 ? 52 : 46;
    if (teams == 8) return total > 8 ? 51 : 46;
    uint32_t ratio = teams ? total / teams : 0;
    if (ratio == 1) return 46;
    if (ratio == 2) return 47;
    if (ratio == 4) return 48;
    if (ratio == 8) return 49;
    if (ratio == 16) return 50;
    return 55;
}

static uint32_t bracket(uint32_t clubs) {
    uint32_t total = 2;
    while (total < clubs && total < 256) total <<= 1;
    return total;
}

static const CalStage* stage_of(uint16_t comp, uint32_t teams) {
    for (uint32_t i = 0; i < COUNT(kCalStages); ++i)
        if (kCalStages[i].comp == comp && kCalStages[i].teams == teams) return &kCalStages[i];
    return NULL;
}

static bool has_stages(uint16_t comp) {
    for (uint32_t i = 0; i < COUNT(kCalStages); ++i) if (kCalStages[i].comp == comp) return true;
    return false;
}

static bool is_single(uint16_t comp) {
    for (uint32_t i = 0; i < COUNT(kCalSingle); ++i) if (kCalSingle[i] == comp) return true;
    return false;
}

// ---------------------------------------------------------------- the rows
typedef void (*dispatch_fn)(uint64_t, void*);
typedef uint64_t (*single_fn)(uint64_t, uint64_t);
typedef void (*push_row_fn)(void*, const DateRow*);
static dispatch_fn g_dispatch_orig = NULL;
static single_fn g_single_orig = NULL;

struct Seen { uint16_t comp; uint16_t n; };
static Seen g_seen[64];
static uint32_t g_nseen = 0;

static void note(uint16_t comp, uint32_t n, const char* what, uint32_t rows) {
    for (uint32_t i = 0; i < g_nseen; ++i) if (g_seen[i].comp == comp && g_seen[i].n == n) return;
    if (g_nseen < COUNT(g_seen)) g_seen[g_nseen++] = {comp, (uint16_t)n};
    char msg[200], when[48] = "no model";
    uintptr_t model = model_base(), at = model + kCalendar + kCalendarDay;
    if (model && readable((const void*)at, 4))
        wsprintfA(when, "calendar day %u year %u", *(const uint16_t*)at, *(const uint16_t*)(at + 2));
    wsprintfA(msg, "ROWS comp %u (%u clubs): %s, %u rows (%s)", comp, n, what, rows, when);
    log_line(msg);
}

static void push(void* rows, uint32_t day, uint32_t code, uint32_t leg) {
    DateRow r = {day, code, leg};
    ((push_row_fn)kPushRowFn)(rows, &r);
}

static bool league_rows(uint16_t comp, void* rows) {
    for (uint32_t i = 0; i < COUNT(kCalLeagues); ++i) {
        const CalLeague& l = kCalLeagues[i];
        if (l.comp != comp) continue;
        uint32_t n = participants(find_comp(model_base(), comp));
        if (n != l.teams) { note(comp, n, "club count differs, native rows", 0); return false; }
        for (uint32_t r = 0; r < l.rounds; ++r) push(rows, l.day[r], r, 2);
        note(comp, n, "league", l.rounds);
        return true;
    }
    return false;
}

static bool explicit_rows(uint16_t comp, void* rows, int max_code) {
    uint32_t pushed = 0;
    for (uint32_t i = 0; i < COUNT(kCalRows); ++i) {
        const CalRow& r = kCalRows[i];
        if (r.comp != comp || (max_code >= 0 && r.code > (uint32_t)max_code)) continue;
        push(rows, r.day, r.code, r.leg);
        ++pushed;
    }
    return pushed != 0;
}

static uint32_t row_day(uint16_t comp, uint32_t code) {
    for (uint32_t i = 0; i < COUNT(kCalRows); ++i)
        if (kCalRows[i].comp == comp && kCalRows[i].code == code) return kCalRows[i].day;
    return 0xFFFF;
}

static bool league_phase_rows(uint16_t base, void* rows) {
    uintptr_t rec = find_comp(model_base(), base);
    uint32_t groups = group_count(rec);
    if (base == 77) {
        if (groups != 9) { note(base, groups, "UECL groups differ, native rows", 0); return false; }
        explicit_rows(base, rows, 5);
        note(base, groups, "Conference League league phase", 6);
        return true;
    }
    if (groups == 4) {                                   // 36 clubs, 8 matchdays + empty ninth round
        explicit_rows(base, rows, 7);
        uint32_t last = row_day(base, 7);
        push(rows, (last + 7) % 365, 8, 2);
        note(base, groups, "league phase (36 clubs)", 9);
        return true;
    }
    if (groups == 8 || groups == 12) {                   // seasons created with the old format
        explicit_rows(base, rows, 5);
        note(base, groups, "old group stage", 6);
        return true;
    }
    note(base, groups, "group count unknown, native rows", 0);
    return false;
}

static bool cup_rows(uint16_t comp, void* rows) {
    uint32_t n = participants(find_comp(model_base(), comp));
    if (n < 2) { note(comp, n, "no clubs yet, native rows", 0); return false; }
    uint32_t total = bracket(n);
    for (uint32_t t = total; t >= 2; t >>= 1)
        if (!stage_of(comp, t)) { note(comp, n, "bracket larger than the table, native rows", 0); return false; }
    uint32_t pushed = 0;
    for (uint32_t t = total; t >= 2; t >>= 1) {
        const CalStage* s = stage_of(comp, t);
        uint32_t code = round_code(total, t);
        if (s->two_legged) {
            push(rows, s->day[0], code, 0);
            push(rows, s->day[1], code, 1);
            pushed += 2;
        } else {
            push(rows, s->day[0], code, 2);
            ++pushed;
        }
    }
    note(comp, n, "cup", pushed);
    return true;
}

static void dispatch_hook(uint64_t comp_arg, void* rows) {
    uint16_t comp = (uint16_t)comp_arg, base = comp & 0x3FF;
    if (rows && readable(rows, 24)) {
        bool done = false;
        if (base == 3 || base == 5 || base == 77) done = league_phase_rows(base, rows);
        else if (comp == base && (base == 4 || base == 6 || base == 78 || base == 83 || base == 84 ||
                 base == 85 || base == 1 || is_single(base))) {
            done = explicit_rows(base, rows, -1);
            note(base, participants(find_comp(model_base(), base)), "fixed rows", 0);
        }
        else if (comp == base && has_stages(base)) done = cup_rows(base, rows);
        else if (comp == base) done = league_rows(base, rows);
        if (done) return;
    }
    g_dispatch_orig(comp_arg, rows);
}

// ------------------------------------------------------- single or two legs
static uint64_t single_hook(uint64_t comp_arg, uint64_t code_arg) {
    uint16_t comp = (uint16_t)comp_arg;
    uint32_t code = (uint32_t)code_arg;
    if (is_single(comp)) return 1;
    if (has_stages(comp)) {
        uint32_t n = participants(find_comp(model_base(), comp));
        if (n >= 2) {
            uint32_t total = bracket(n);
            for (uint32_t t = total; t >= 2; t >>= 1) {
                if (round_code(total, t) != code) continue;
                const CalStage* s = stage_of(comp, t);
                if (s) return s->two_legged ? 0 : 1;
            }
        }
    }
    return g_single_orig(comp_arg, code_arg);
}

static bool g_installed = false;

extern "C" __declspec(dllexport) int euro_extra_install(void) {
    if (!g_log_ready) { InitializeCriticalSection(&g_log_lock); g_log_ready = true; }
    log_line("LOADED euro_extra 0.2.0 (real 2025/26 calendar, >= 3 days between matches; real cup legs;"
             " Conference League 77/78, EFL Cup 139, Taca da Liga 144, Scottish League Cup 146)");
    if (g_installed) return 6;
    if ((uintptr_t)GetModuleHandleW(NULL) != kImageBase) { log_line("ABORT unexpected base"); return 1; }
    HMODULE self = NULL;
    GetModuleHandleExW(GET_MODULE_HANDLE_EX_FLAG_PIN | GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS,
        (LPCWSTR)&dispatch_hook, &self);
    g_installed = true;
    g_dispatch_orig = (dispatch_fn)hook_entry(kDispatcher, kDispatcherSig, sizeof(kDispatcherSig), (void*)&dispatch_hook);
    log_line(g_dispatch_orig ? "PATCHED date dispatcher" : "ABORT date dispatcher: prologue differs");
    g_single_orig = (single_fn)hook_entry(kSingleMatch, kSingleSig, sizeof(kSingleSig), (void*)&single_hook);
    log_line(g_single_orig ? "PATCHED single/two-legged rounds" : "ABORT single/two-legged rounds: prologue differs");
    int missing = (g_dispatch_orig ? 0 : 1) + (g_single_orig ? 0 : 1);
    char msg[160];
    wsprintfA(msg, "INSTALLED: %u league tables, %u fixed rows, %u cup stages%s",
        (unsigned)COUNT(kCalLeagues), (unsigned)COUNT(kCalRows), (unsigned)COUNT(kCalStages),
        missing ? " (missing hooks)" : "");
    log_line(msg);
    return missing ? 2 : 0;
}

BOOL APIENTRY DllMain(HMODULE mod, DWORD reason, LPVOID) {
    if (reason == DLL_PROCESS_ATTACH) DisableThreadLibraryCalls(mod);
    return TRUE;
}
